'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Gift as GiftIcon, Search, ArrowUpRight, Bell, Plus, RefreshCw, Check, SlidersHorizontal, Link as LinkIcon, CalendarDays, Wallet, ChevronRight, Pencil, Trash2, ShieldCheck, CircleAlert, TrendingDown } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { money, rankOffers, type Gift, type Alert, type Offer } from '@/lib/model';
import { nextBlackFriday, plannedCost, chosenOffer, valueAdvice } from '@/lib/planning';
type Group={id:string;name:string};
type Data={gifts:Gift[];alerts:Alert[];groups:Group[];budget:number;searchReady:boolean;monitorHeartbeat:string|null};
const empty:Data={gifts:[],alerts:[],groups:[{id:'my',name:'My family'},{id:'liv',name:'Liv’s family'},{id:'other',name:'Other'}],budget:0,searchReady:false,monitorHeartbeat:null};
const stamp=(v:string|null)=>v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not yet checked';
export default function Dashboard({signedIn,signInUrl}:{signedIn:boolean;signInUrl:string}){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(signedIn),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [group,setGroup]=useState('all'),[mode,setMode]=useState('search'),[query,setQuery]=useState(''),[name,setName]=useState(''),[recipient,setRecipient]=useState(''),[url,setUrl]=useState(''),[plan,setPlan]=useState(''),[threshold,setThreshold]=useState('15'),[formGroup,setFormGroup]=useState('');
 const [view,setView]=useState<Gift|null>(null),[editing,setEditing]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[budgetInput,setBudgetInput]=useState(''),[groupEdits,setGroupEdits]=useState<Record<string,string>>({}),[newGroup,setNewGroup]=useState(''),[today,setToday]=useState(new Date());
 const autoChecked=useRef(new Set<string>());
 const load=useCallback(async()=>{if(!signedIn)return;const r=await fetch('/api/dashboard');const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error||'Your list could not be loaded.');d.gifts=d.gifts.map((g:Gift)=>({...g,offers:rankOffers(g.offers)}));setData(d);setLoading(false);return d as Data;},[signedIn]);
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false)});const timer=setInterval(()=>{setToday(new Date());if(document.visibilityState==='visible')load().catch(()=>{});},60000);return()=>clearInterval(timer);},[load]);
 const act=useCallback(async(body:Record<string,unknown>)=>{if(!signedIn)throw new Error('Sign in to save your gift list.');const r=await fetch('/api/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json() as {error?:string;id?:string;ok?:boolean};if(!r.ok)throw new Error(v.error||'Could not save.');await load();return v;},[signedIn,load]);
 async function run(body:Record<string,unknown>,message='Saved'){setBusy(true);setError('');try{const r=await act(body);setNotice(message);return r;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 useEffect(()=>{if(!signedIn||busy||loading)return;const stale=data.gifts.find(g=>g.status==='watching'&&!autoChecked.current.has(g.id)&&(!g.last_checked||Date.now()-Date.parse(g.last_checked)>6*3600000));if(!stale)return;autoChecked.current.add(stale.id);act({action:'refresh',id:stale.id}).catch(()=>{});},[signedIn,busy,loading,data.gifts,act]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context)return;const life=new AbortController();
 const tool={name:'save_gift',description:'Save a gift in the signed-in user’s selected family group and check offers. Does not purchase anything.',inputSchema:{type:'object',properties:{name:{type:'string'},recipient:{type:'string'},query:{type:'string'},url:{type:'string'},groupId:{type:'string'}},required:['name','recipient','groupId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object')throw new Error('Gift fields are required.');const b=input as Record<string,unknown>;if(typeof b.name!=='string'||typeof b.recipient!=='string'||typeof b.groupId!=='string'||(!b.query&&!b.url))throw new Error('Provide name, recipient, groupId, and query or URL.');return await act({...b,action:'add'});}};
 Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});return()=>life.abort();},[act]);
 const bf=nextBlackFriday(today),gifts=data.gifts.filter(g=>group==='all'||g.group_id===group),alerts=data.alerts.filter(a=>gifts.some(g=>g.id===a.gift_id));
 const allTotal=data.gifts.reduce((s,g)=>s+(plannedCost(g)||0),0),total=gifts.reduce((s,g)=>s+(plannedCost(g)||0),0),remaining=data.budget-allTotal,over=data.budget>0&&remaining<0,used=data.budget>0?allTotal/data.budget*100:0;
 const unknown=data.gifts.filter(g=>plannedCost(g)===null).length;const groupName=group==='all'?'All gifts':data.groups.find(g=>g.id===group)?.name||'All gifts';
 const advice=gifts.filter(g=>g.status!=='purchased').map(g=>({g,...valueAdvice(g,data.budget,over)})).sort((a,b)=>b.priority-a.priority);
 const monitorActive=!!data.monitorHeartbeat&&Date.now()-Date.parse(data.monitorHeartbeat)<3*3600000;
 async function add(e:React.FormEvent){e.preventDefault();const r=await run({action:'add',name:name||query,recipient,query:mode==='search'?query:'',url:mode==='link'?url:'',groupId:formGroup||(group!=='all'?group:data.groups[0]?.id),plannedPrice:plan,threshold},'Gift saved. Price checks will keep running in the background.');if(r){setQuery('');setName('');setRecipient('');setUrl('');setPlan('');}}
 function openGift(g:Gift){setView(g);setEditing(false);setName(g.name);setRecipient(g.recipient);setPlan(g.planned_price?.toString()||'');setThreshold(String(g.threshold));setFormGroup(g.group_id);}
 const current=view?data.gifts.find(g=>g.id===view.id)||view:null;
 function openSettings(){setBudgetInput(String(data.budget||''));setGroupEdits(Object.fromEntries(data.groups.map(g=>[g.id,g.name])));setSettingsOpen(true);}
 return <div className="app-shell">
  <a href="#planner" className="skip-link">Skip to gift planner</a>
  <header className="masthead"><a className="brand" href="/" aria-label="Christmas gifts 2026 home"><span className="brand-icon"><GiftIcon size={23}/></span><span>Christmas gifts <b>2026</b></span></a><div className="header-right"><span className="private-note"><ShieldCheck size={16}/> Your list stays private</span>{signedIn?<a className="quiet-link" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a>:<a className="signin" href={signInUrl} target="_top">Sign in with ChatGPT <ArrowUpRight size={16}/></a>}</div></header>
  <main id="planner" className="workspace">
   <section className="heading-row"><div><p className="eyebrow">A LITTLE THOUGHT. A BETTER DEAL.</p><h1>The gift watchlist<span>.</span></h1><p className="intro">Find the right gift. Let the price come to you.</p></div><div className="countdown"><CalendarDays size={22}/><div><span className="count-label">NEXT BLACK FRIDAY · {bf.date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})}</span><div><strong>{bf.days===0?'Today':bf.days}</strong> <span>{bf.days===0?'Time to check your final offers':'days to find a great deal'}</span></div>{bf.rolled&&<small>This year’s event has passed; planning for next year.</small>}</div></div></section>
   <div className="group-row"><div className="group-tabs" aria-label="Filter gifts by group"><button className={group==='all'?'selected':''} aria-pressed={group==='all'} onClick={()=>setGroup('all')}>All gifts <span>{data.gifts.length}</span></button>{data.groups.map(g=><button key={g.id} className={group===g.id?'selected':''} aria-pressed={group===g.id} onClick={()=>{setGroup(g.id);setFormGroup(g.id)}}>{g.name}<span>{data.gifts.filter(x=>x.group_id===g.id).length}</span></button>)}</div><button className="text-button" onClick={openSettings}><SlidersHorizontal size={16}/> Budget & groups</button></div>
   <section className="budget-bar" aria-label="Budget overview"><div className="budget-main"><span className="mini-label">OVERALL BUDGET · ALL GROUPS</span><button className="budget-number" onClick={openSettings}>{data.budget?money(data.budget):'Set your budget'}<Pencil size={14}/></button><div className="meter" role="progressbar" aria-label="Overall budget used" aria-valuenow={Math.round(Math.min(100,used))} aria-valuemin={0} aria-valuemax={100}><span className={over?'over':''} style={{width:Math.min(100,used)+'%'}}/></div><small>{data.budget?`${Math.round(used)}% planned${over?' · Over budget':''}`:'An amount you feel good about.'}</small></div><div><span className="mini-label">TOTAL PLANNED</span><strong>{money(allTotal)}</strong><small>{unknown?`${unknown} gift${unknown===1?'':'s'} still need a price`:'USD · shipping included when known; tax extra'}</small></div><div><span className="mini-label">{over?'OVER BUDGET':'REMAINING'}</span><strong className={over?'negative':''}>{data.budget?money(Math.abs(remaining)):'—'}</strong><small>Across every group</small></div><div><span className="mini-label">{groupName.toUpperCase()}</span><strong>{money(total)}</strong><small>{gifts.filter(g=>g.status==='purchased').length} of {gifts.length} gifts purchased</small></div></section>
   <div className="feedback" aria-live="polite">{notice&&<p className="success"><Check size={16}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></p>}</div>{error&&<div role="alert" className="error-box">{error} <button onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Retry loading</button></div>}
   <div className="content-grid"><div className="primary-column">
    <section className="add-panel"><div className="section-head"><div><p className="eyebrow">START WITH A GOOD IDEA</p><h2>What’s on their list?</h2></div><span className="step-pill">01 / FIND & WATCH</span></div><div className="mode-tabs" role="group" aria-label="How to add a gift"><button aria-pressed={mode==='search'} className={mode==='search'?'active':''} onClick={()=>setMode('search')}><Search size={16}/> Find a product</button><button aria-pressed={mode==='link'} className={mode==='link'?'active':''} onClick={()=>setMode('link')}><LinkIcon size={16}/> I have a link</button></div>
     <form onSubmit={add}><label className="field main-field"><span>{mode==='search'?'Product name or description':'Product / store URL'}</span><div className="input-icon">{mode==='search'?<Search size={20}/>:<LinkIcon size={20}/>}<input required type={mode==='search'?'text':'url'} value={mode==='search'?query:url} onChange={e=>mode==='search'?setQuery(e.target.value):setUrl(e.target.value)} placeholder={mode==='search'?'e.g. Sony WH-1000XM6 headphones, black':'https://store.com/product'} maxLength={mode==='search'?240:2000}/></div></label>
      <div className="form-row"><label className="field"><span>For whom?</span><input required value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Recipient’s name" maxLength={100}/></label><label className="field"><span>Group</span><select value={formGroup||(group!=='all'?group:data.groups[0]?.id)} onChange={e=>setFormGroup(e.target.value)}>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label></div>
      <details className="extra-fields"><summary>Gift name, planned price & alert threshold</summary><div className="form-row"><label className="field"><span>Gift name {mode==='search'?'(optional)':''}</span><input required={mode==='link'} value={name} onChange={e=>setName(e.target.value)} placeholder="A name for your list" maxLength={160}/></label><label className="field"><span>Planned / paid amount (USD)</span><input type="number" step=".01" min="0" max="1000000" value={plan} onChange={e=>setPlan(e.target.value)} placeholder="Use live price"/></label><label className="field"><span>Alert on observed drop</span><select value={threshold} onChange={e=>setThreshold(e.target.value)}>{[5,10,15,20,25,30,40,50].map(v=><option key={v} value={v}>{v}% or more</option>)}</select></label></div></details>
      {mode==='search'&&!data.searchReady&&<p className="connection-note"><CircleAlert size={16}/><span>Offer search needs a shopping-data connection. Save an idea now, or use a store link to begin price tracking.</span></p>}
      <div className="form-footer"><span>Specific models make for better matches.</span>{signedIn?<button type="submit" className="primary-button" disabled={busy||loading}>{busy?<RefreshCw className="spin" size={17}/>:<Plus size={17}/>} {busy?'Saving & checking…':mode==='search'?'Save & compare':'Save & track'}</button>:<a className="primary-button" href={signInUrl} target="_top">Sign in to save gifts <ArrowUpRight size={17}/></a>}</div>
     </form>
    </section>
    <section className="watchlist"><div className="section-head"><div><p className="eyebrow">{groupName.toUpperCase()}</p><h2>Gifts worth watching <span className="count-badge">{gifts.length}</span></h2></div><span className="muted">{gifts.filter(g=>g.status==='watching').length} watching</span></div>
     {loading?<p className="empty-state">Loading your gift list…</p>:!gifts.length?<div className="empty-state"><span className="empty-icon"><GiftIcon size={32} strokeWidth={1.4}/></span><h3>A thoughtful Christmas starts here.</h3><p>Add a product idea or store link above.<br/>Your gifts, prices and best opportunities will gather here.</p><span className="empty-rule">SAVE AN IDEA <ChevronRight size={14}/> COMPARE OFFERS <ChevronRight size={14}/> BUY AT THE RIGHT TIME</span></div>:<div className="gift-list">{gifts.map(g=>{const o=chosenOffer(g),a=valueAdvice(g,data.budget,over),h=o?g.history.filter(x=>x.offer_id===o.id&&x.currency===o.currency):[];const prev=h[1]?.price;return <article className="gift-card" key={g.id}><div className="gift-card-top"><div className="recipient-avatar">{g.recipient.slice(0,1).toUpperCase()}</div><div className="gift-title"><span className="mini-label">FOR {g.recipient.toUpperCase()} · {data.groups.find(x=>x.id===g.group_id)?.name}</span><button onClick={()=>openGift(g)}>{g.name}</button></div><span className={'status '+(g.status==='purchased'?'bought':g.error?'needs-attention':'')}>{g.status==='purchased'?'Purchased':g.error?'Needs attention':a.early?'Early-buy candidate':'Watching'}</span></div><div className="gift-card-body"><div><span className="mini-label">{g.last_success?'LAST OBSERVED PRICE':'CURRENT PRICE'}</span><strong>{money(g.current_price,g.currency)}</strong><small>{prev!==undefined?`Previous: ${money(prev,g.currency)}`:g.last_success?'Building price history':'Waiting for reliable data'}</small></div><div><span className="mini-label">BUDGET SHARE</span><strong>{data.budget&&a.cost!==null?`${Math.round(a.impact*100)}%`:'—'}</strong><small>{a.cost!==null?`${money(a.cost)} planned${g.planned_price!==null?' · entered amount':''}`:'Add an estimate to plan ahead'}</small></div><div><span className="mini-label">BEST DEAL SCORE</span><strong>{g.offers[0]?.score!==undefined?`${g.offers[0].score}/100`:'—'}</strong><small>{g.offers.length?`${g.offers.length} offer${g.offers.length===1?'':'s'} compared`:'No offer comparison yet'}</small></div></div>{g.error&&<p className="gift-warning">{g.error}</p>}<div className="gift-card-footer"><span className="muted">{g.last_success?`Price checked ${stamp(g.last_success)}`:g.last_checked?`Check attempted ${stamp(g.last_checked)}`:'Waiting for first check'}</span><button className="text-button" onClick={()=>openGift(g)}>Compare & manage <ChevronRight size={16}/></button></div></article>;})}</div>}
    </section>
   </div><aside className="insights"><section className="strategy-card"><p className="eyebrow">THE PLAN</p><h2>Patient shopping.<br/><em>Thoughtful giving.</em></h2><p>Aim for Black Friday. Buy early only when an observed price drop and a strong offer make it worthwhile.</p><div className="strategy-rule"><TrendingDown size={19}/><span>Default alert: <b>15% below an observed high</b></span></div></section>
    <section className="side-panel"><div className="side-heading"><Bell size={18}/><h2>Deal alerts</h2><span className="count-badge">{alerts.filter(a=>!a.seen).length}</span></div>{alerts.length?<><div className="alert-list">{alerts.slice(0,8).map(a=><article className={a.seen?'read':''} key={a.id}><p>{a.message}</p><small>{stamp(a.created_at)}</small><button className="text-button" onClick={()=>{const g=data.gifts.find(g=>g.id===a.gift_id);if(g)openGift(g);}}>Review gift <ChevronRight size={14}/></button></article>)}</div><button disabled={busy} className="text-button" onClick={()=>run({action:'seen',ids:alerts.map(a=>a.id)},'Alerts marked as read')}>Mark these alerts read</button></>:<div className="small-empty"><p>No deal alerts yet.</p><span>Significant observed price drops for {group==='all'?'your gifts':'this group'} will appear here.</span></div>}</section>
    <section className="side-panel"><div className="side-heading"><Wallet size={18}/><h2>{over?'Bring the plan back in budget':'Budget & value'}</h2></div>{advice.length?advice.slice(0,3).map(a=><div className="advice" key={a.g.id}><button onClick={()=>openGift(a.g)}>{a.g.name}<ChevronRight size={14}/></button><span className="recommendation">Recommendation · {a.label}</span><p>{a.detail}</p>{a.savings>0&&<strong>Potential saving: {money(a.savings,a.g.currency)}</strong>}</div>):<p className="muted">As your list grows, see which gifts offer good value and which deserve another look.</p>}<div className="group-totals">{data.groups.map(g=><div key={g.id}><span>{g.name}</span><b>{money(data.gifts.filter(x=>x.group_id===g.id).reduce((s,x)=>s+(plannedCost(x)||0),0))}</b></div>)}</div></section>
    <section className="monitor-note"><ShieldCheck size={18}/><div><b>{monitorActive?'Background checks are running':'Automatic checks run when you open the dashboard'}</b><p>{monitorActive?'Active gifts are checked about every 6 hours, including while you’re away.':'Stale active gifts refresh one at a time while the dashboard is open. Continuous checks while it is closed still need a scheduler connection.'} {data.monitorHeartbeat?`Last monitor run: ${stamp(data.monitorHeartbeat)}.`:''} Retailers may block checks or omit prices.</p><p>Alerts appear here. Email and push are not connected.</p></div></section>
   </aside></div>
   <footer className="page-footer"><span>Christmas gifts 2026</span><span>Prices are observations, not guarantees. Confirm variants, shipping and checkout totals.</span></footer>
  </main>
  <Dialog open={!!current} onOpenChange={open=>{if(!open){setView(null);setEditing(false);setName('');setRecipient('');setPlan('');}}}><DialogContent className="detail-dialog"><DialogTitle>{current?.name}</DialogTitle><DialogDescription>Compare offers, review the history, and decide when to buy.</DialogDescription>{current&&<>
   <div className="detail-actions"><span>For {current.recipient}</span><button className="text-button" disabled={busy} onClick={()=>run({action:'refresh',id:current.id},'Price check completed. Check the result below.')}><RefreshCw size={16}/> Check prices</button><button className="text-button" onClick={()=>setEditing(!editing)}><Pencil size={16}/> Edit</button><button className="primary-button" disabled={busy} onClick={()=>run({action:'status',id:current.id,status:current.status==='purchased'?'watching':'purchased'},current.status==='purchased'?'Watching again':'Marked purchased')}><Check size={16}/>{current.status==='purchased'?'Watch again':'Mark purchased'}</button></div>
   {editing&&<form className="edit-form" onSubmit={async e=>{e.preventDefault();const r=await run({action:'edit',id:current.id,name,recipient,groupId:formGroup,plannedPrice:plan,threshold});if(r)setEditing(false);}}><div className="form-row"><label className="field"><span>Gift name</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label className="field"><span>Recipient</span><input value={recipient} onChange={e=>setRecipient(e.target.value)} required/></label></div><div className="form-row"><label className="field"><span>Group</span><select value={formGroup} onChange={e=>setFormGroup(e.target.value)}>{data.groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label><label className="field"><span>Planned / paid amount (USD)</span><input type="number" step=".01" min="0" max="1000000" value={plan} onChange={e=>setPlan(e.target.value)} placeholder="Use live price"/></label><label className="field"><span>Alert drop (%)</span><input type="number" min="5" max="80" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label></div><button className="primary-button" disabled={busy}>Save changes</button></form>}
   {current.error&&<p className="connection-note">{current.error}</p>}{current.url&&<a className="text-button" href={current.url} target="_blank" rel="noopener noreferrer">Open saved store link <ArrowUpRight size={15}/></a>}
   <details className="score-explainer"><summary>How the Best Deal score works</summary><p>A recommendation out of 100: cost including known shipping (30), product word match (25), seller reliability (20), advertised discount (10), delivery timing (5), and freshness (10). Unknown shipping or seller reputation lowers the score. Familiar retail domains earn partial reliability credit, not a guarantee. Product reviews are never used as seller reviews. Comparisons exclude tax and never convert BOGO to a made-up discount. Verify variants and eligibility yourself.</p></details>
   <div className="offers">{current.offers.length?current.offers.map((o,i)=><OfferCard key={o.id} offer={o} top={i===0} selected={chosenOffer(current)?.id===o.id} disabled={busy} onChoose={()=>run({action:'choose',id:current.id,offerId:o.id},'Offer selected for your plan')}/>):<div className="small-empty"><h3>No verified offers yet</h3><p>{current.query?'Your product idea is saved. Search will compare sellers when the shopping-data connection is available.':'We’ll retry the store. You can enter a planned amount while waiting.'}</p>{current.query&&<a className="text-button" target="_blank" rel="noopener noreferrer" href={'https://www.google.com/search?tbm=shop&q='+encodeURIComponent(current.query)}>Browse Google Shopping <ArrowUpRight size={15}/></a>}</div>}</div>
   <section className="history"><h3>Observed price history</h3><p className="muted">Your own checks, distinct from a seller’s advertised “was” price. Latest 120 observations.</p>{current.history.length?<div className="table-scroll"><table><thead><tr><th>Checked</th><th>Seller / offer</th><th>Price</th></tr></thead><tbody>{current.history.slice(0,30).map(h=><tr key={h.id}><td>{stamp(h.checked_at)}</td><td>{h.seller}<small>{current.offers.find(o=>o.id===h.offer_id)?.title||'Previously observed offer'}</small></td><td>{money(h.price,h.currency)}</td></tr>)}</tbody></table></div>:<p className="muted">History starts with the first reliable price check.</p>}</section><details className="remove-gift"><summary><Trash2 size={15}/> Remove this gift</summary><p>This permanently removes the gift and its recorded history.</p><button className="danger-button" disabled={busy} onClick={async()=>{if(await run({action:'delete',id:current.id},'Gift removed'))setView(null);}}>Remove gift and history</button></details>
   {error&&<p role="alert" className="error-box">{error}</p>}
  </>}</DialogContent></Dialog>
  <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="settings-dialog"><DialogTitle>Budget & groups</DialogTitle><DialogDescription>One overall budget. A thoughtful list for every group.</DialogDescription>{!signedIn?<a className="primary-button" href={signInUrl} target="_top">Sign in to personalize</a>:<><form onSubmit={e=>{e.preventDefault();run({action:'budget',amount:budgetInput},'Overall budget saved');}}><label className="field"><span>Overall gift budget (USD)</span><input required type="number" min="0" max="1000000" step=".01" value={budgetInput} onChange={e=>setBudgetInput(e.target.value)} placeholder="e.g. 1000"/></label><button className="primary-button" disabled={busy}>Save budget</button></form><h3>Your groups</h3>{data.groups.map(g=><form className="group-edit" key={g.id} onSubmit={e=>{e.preventDefault();run({action:'group',id:g.id,name:groupEdits[g.id]},'Group renamed');}}><label className="sr-only" htmlFor={'group-'+g.id}>Rename {g.name}</label><input id={'group-'+g.id} required value={groupEdits[g.id]??g.name} onChange={e=>setGroupEdits({...groupEdits,[g.id]:e.target.value})} maxLength={60}/><button className="secondary-button" disabled={busy}>Save</button></form>)}<form className="group-edit" onSubmit={async e=>{e.preventDefault();if(await run({action:'group',name:newGroup},'Group added'))setNewGroup('');}}><label className="sr-only" htmlFor="new-group">New group name</label><input id="new-group" required placeholder="New group, e.g. Friends" value={newGroup} onChange={e=>setNewGroup(e.target.value)} maxLength={60}/><button className="secondary-button" disabled={busy}><Plus size={15}/> Add</button></form><p className="muted">Budget totals use entered amounts when set, otherwise the selected live offer plus known shipping. Unknown shipping, tax and gifts without prices are not included. Non-USD gifts need a USD estimate.</p></>}{error&&<p role="alert" className="error-box">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}</DialogContent></Dialog>
 </div>;
}
function OfferCard({offer:o,top,selected,disabled,onChoose}:{offer:Offer;top:boolean;selected:boolean;disabled:boolean;onChoose:()=>unknown}){return <article className={'offer-card '+(top?'top-offer':'')}><div className="offer-heading"><div><span className="mini-label">{top?'TOP SCORED CANDIDATE':'COMPARE OFFER'} · {o.seller}</span><h3>{o.title}</h3></div><div className="score"><strong>{o.score}</strong><span>/100</span></div></div><div className="offer-numbers"><strong>{money(o.price,o.currency)}</strong>{o.oldPrice&&o.oldPrice>o.price&&<span>Seller’s prior price: <s>{money(o.oldPrice,o.currency)}</s></span>}<span>{o.shipping===null?'Shipping unknown':o.shipping===0?'Free shipping':`+ ${money(o.shipping,o.currency)} shipping`}</span><b>{o.shipping===null?'Total incomplete':`${money(o.price+o.shipping,o.currency)} before tax`}</b></div>{o.deal&&<p className="deal-tag">{o.deal}</p>}<p className="muted">{o.condition} · {o.delivery}</p><p className="muted">{Math.round(o.match*100)}% word match · {o.source} · checked {stamp(o.fetchedAt)}</p><details><summary>{top?'Why this offer ranks first':'Score & confidence details'}</summary><p>Score contributions: {Object.entries(o.parts||{}).map(([k,v])=>`${k} ${v}`).join(' · ')}. {top?'Highest weighted score among the currently returned candidates; not a guarantee of the best offer anywhere.':''}</p><ul>{o.reasons?.map(x=><li key={x}>{x}</li>)}</ul></details><div className="offer-actions"><button className="secondary-button" disabled={disabled||selected} onClick={onChoose}>{selected?<><Check size={15}/> In your plan</>:'Use this offer'}</button><a className="primary-button" href={o.url} target="_blank" rel="noopener noreferrer">{o.direct?'Visit store':'View shopping listing'}<ArrowUpRight size={15}/></a></div></article>;}


